### PR TITLE
deps: Update `eframe`, `image`. `notify`

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This changes the constraints demo so that it fills the window and is a bit more likely the sample code for eframe. It is kind of janky though when I run it, but it seemed janky before I updated things as well.

**Comment by mkeeter** [comment]
The `eframe` update is unfortunate – previously, the egui demo was constrained to a specific `canvas`, so it could be embedded into a large webpage (mostly written in normal HTML).  The idea here is that I could embed multiple small demos into a blog post; I'd like to keep this property.

(`eframe` upstream hasn't emphasized this use case, so it's not surprising that they've broken it by accident)

I'd rather leave the `eframe` dependency as-is, since I don't have time to dig into the internals and figure out what changed.  Updating `image` and `notify` seems fine to me!

**Comment by waywardmonkeys** [comment]
If that's important, then I'll look into that.

The updates go well together since they get rid of a few duplicated dependencies, especially on Windows where it gets rid of a whole version of one of the Windows binding crates.

**Comment by waywardmonkeys** [comment]
Okay, fixed it and will be updating shortly.

**Comment by waywardmonkeys** [comment]
Your use case was one that they specifically fixed / improved in eframe 0.28!

**Comment by waywardmonkeys** [comment]
Maybe the last update is better!

**Comment by mkeeter** [comment]
Looks good!  I restored the outer `div` to make sure it worked and found that we could minimize the CSS somewhat.

**Pull request merged**
